stages:
  - packndeploy

image: stephenmai45/alpine:latest

cache:
  paths:
    - vendor/
    - worknook_admin.zip

packndeploy_laravel:
  tags:
    - cicd
    - devops
    - worknook
  stage: packndeploy
  before_script:
    - source .${CI_COMMIT_REF_NAME}.env
    - apk update && apk upgrade
    - eval $(ssh-agent -s)
    - apk add openssh-client
    - ssh-add <(echo "$WORKNOOK_ADMIN_INSTANCE_KEY")
  script:
    - echo "Creating ZIP file for $ZIP_FILE_ADMIN"
    - zip -r $ZIP_FILE_ADMIN *
    - ls -lah
    - sftp -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST <<< $'put '"$ZIP_FILE_ADMIN"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'yes | unzip '"$ZIP_FILE_ADMIN"' -d '"$WORKNOOK_ADMIN_DEPLOY_TEMP"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'rsync -av '"$WORKNOOK_ADMIN_DEPLOY_TEMP $WORKNOOK_ADMIN_DEPLOY_DIR"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'export COMPOSER_ALLOW_SUPERUSER=1'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'cd '"$WORKNOOK_ADMIN_DEPLOY_DIR_COMPOSER"' && composer install'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'cd '"$WORKNOOK_ADMIN_DEPLOY_DIR_COMPOSER"' && php artisan config:clear'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'cd '"$WORKNOOK_ADMIN_DEPLOY_DIR_COMPOSER"' && npm install --force'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'cd '"$WORKNOOK_ADMIN_DEPLOY_DIR_COMPOSER"' && npm run dev'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'chown -R '"$WORKNOOK_ADMIN_INSTANCE_OWNED"' '"$WORKNOOK_ADMIN_DEPLOY_DIR_COMPOSER"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'chmod -R 755 '"$WORKNOOK_ADMIN_DEPLOY_DIR_COMPOSER"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'rm -rf '"$WORKNOOK_ADMIN_DEPLOY_TEMP"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'rm -f '"$ZIP_FILE_ADMIN"
    - rm -f $ZIP_FILE_ADMIN
  only:
    - staging
