stages:
  - packndeploy

image: faisaladiprayugo/ubuntu:v5

cache:
  paths:
    - vendor/
    - worknook_admin.zip

packndeploy_laravel:
  tags:
    - cicd
    - devops
    - worknook
  stage: packndeploy
  before_script:
    - source .${CI_COMMIT_REF_NAME}.env
    - apt update -y
    - dpkg-query -W --showformat='${Status}\n' zip | grep "install ok installed" || install zip -y
    - dpkg-query -W --showformat='${Status}\n' unzip | grep "install ok installed" || install unzip -y
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$WORKNOOK_ADMIN_INSTANCE_KEY")
  script:
    - echo "Creating ZIP file for $ZIP_FILE_ADMIN"
    - zip -r $ZIP_FILE_ADMIN *
    - ls -lah
    - sftp -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST <<< $'put '"$ZIP_FILE_ADMIN"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'yes | unzip '"$ZIP_FILE_ADMIN"' -d '"$WORKNOOK_ADMIN_DEPLOY_TEMP"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'rsync -av '"$WORKNOOK_ADMIN_DEPLOY_TEMP $WORKNOOK_ADMIN_DEPLOY_DIR"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'cd '"$WORKNOOK_ADMIN_DEPLOY_DIR"' && export COMPOSER_ALLOW_SUPERUSER=1'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'cd '"$WORKNOOK_ADMIN_DEPLOY_DIR"' && composer install'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'cd '"$WORKNOOK_ADMIN_DEPLOY_DIR"' && $(which php8.1) artisan migrate'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'cd '"$WORKNOOK_ADMIN_DEPLOY_DIR"' && $(which php8.1) artisan config:clear'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'chown -R '"$WORKNOOK_ADMIN_INSTANCE_OWNED"' '"$WORKNOOK_ADMIN_DEPLOY_DIR"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'chmod -R 755 '"$WORKNOOK_ADMIN_DEPLOY_DIR"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'rm -rf '"$WORKNOOK_ADMIN_DEPLOY_TEMP"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_ADMIN_INSTANCE_USER@$WORKNOOK_ADMIN_INSTANCE_HOST 'rm -f '"$ZIP_FILE_ADMIN"
    - rm -f $ZIP_FILE_ADMIN
  only:
    - staging
