stages:
  - packndeploy

image: faisaladiprayugo/ubuntu:v5

cache:
  paths:
    - vendor/
    - worknook_api.zip

packndeploy_laravel:
  tags:
    - cicd
    - devops
    - worknook
  stage: packndeploy
  before_script:
    - source .${CI_COMMIT_REF_NAME}.env
    - apt update -y
    - dpkg-query -W --showformat='${Status}\n' zip | grep "install ok installed" || install zip -y
    - dpkg-query -W --showformat='${Status}\n' unzip | grep "install ok installed" || install unzip -y
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$WORKNOOK_API_INSTANCE_KEY")
  script:
    - echo "Creating ZIP file for $ZIP_FILE"
    - zip -r $ZIP_FILE *
    - ls -lah
    - sftp -o StrictHostKeyChecking=no $WORKNOOK_API_INSTANCE_USER@$WORKNOOK_API_INSTANCE_HOST <<< $'put '"$ZIP_FILE"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_API_INSTANCE_USER@$WORKNOOK_API_INSTANCE_HOST 'yes | unzip '"$ZIP_FILE"' -d '"$WORKNOOK_API_DEPLOY_TEMP"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_API_INSTANCE_USER@$WORKNOOK_API_INSTANCE_HOST 'rsync -av '"$WORKNOOK_API_DEPLOY_TEMP $WORKNOOK_API_DEPLOY_DIR"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_API_INSTANCE_USER@$WORKNOOK_API_INSTANCE_HOST 'cd '"$WORKNOOK_API_DEPLOY_DIR"' && $(which php8.1) artisan migrate'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_API_INSTANCE_USER@$WORKNOOK_API_INSTANCE_HOST 'cd '"$WORKNOOK_API_DEPLOY_DIR"' && $(which php8.1) artisan config:clear'
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_API_INSTANCE_USER@$WORKNOOK_API_INSTANCE_HOST 'chown -R '"$WORKNOOK_API_INSTANCE_OWNED"' '"$WORKNOOK_API_DEPLOY_DIR"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_API_INSTANCE_USER@$WORKNOOK_API_INSTANCE_HOST 'chmod -R 755 '"$WORKNOOK_API_DEPLOY_DIR"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_API_INSTANCE_USER@$WORKNOOK_API_INSTANCE_HOST 'rm -rf '"$WORKNOOK_API_DEPLOY_TEMP"
    - ssh -o StrictHostKeyChecking=no $WORKNOOK_API_INSTANCE_USER@$WORKNOOK_API_INSTANCE_HOST 'rm -f '"$ZIP_FILE"
    - rm -f $ZIP_FILE
  only:
    - staging
